# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b46f7fa7ced205bd2235aa0e5a456ec31410f5bfef617a5c5403358644d5a7c28f149277708c48aaa6d5be4d02a6c8a7d19f9ee0a4d77a83688d7f825566419

test:
  secret_key_base: 0043f0acfa5d3522715e8f0135a321f451c542cf30c3e694ff86b44811a0858cd7253a99f0387f0a3b3a4906f5417748d5585e03f9b4f57d5cbf118e43096d51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
